# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# A sample workflow which sets up periodic OSV-Scanner scanning for vulnerabilities,
# in addition to a PR check which fails if new vulnerabilities are introduced.
#
# For more examples and options, including how to ignore specific vulnerabilities,
# see https://google.github.io/osv-scanner/github-action/

name: OSV-Scanner

on:
  pull_request:
    branches: [ "master" ]
  merge_group:
    branches: [ "master" ]
  schedule:
    - cron: '36 22 * * 5'
  push:
    branches: [ "master" ]

permissions:
  security-events: write
  contents: read

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate file list
        run: |
          find . -type f \( -name "*.c" -o -name "*.cpp" -o -name "*.h" \) > scanned_files.txt

      - name: Upload file list artifact
        uses: actions/upload-artifact@v3
        with:
          name: scanned-files
          path: scanned_files.txt

      - name: Run OSV-Scanner
        uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78"
        with:
          scan-args: |
            -r
            --skip-git
            ./

  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate file list
        run: |
          find . -type f \( -name "*.c" -o -name "*.cpp" -o -name "*.h" \) > scanned_files.txt

      - name: Upload file list artifact
        uses: actions/upload-artifact@v3
        with:
          name: scanned-files
          path: scanned_files.txt

      - name: Run OSV-Scanner (PR)
        uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78"
        with:
          scan-args: |
            -r
            --skip-git
            ./
